@MyProject.Api_HostAddress = http://localhost:5206

# GET request to fetch questions
GET {{MyProject.Api_HostAddress}}/api/questionnaire/

# GET request to fetch top 10 high scores
GET {{MyProject.Api_HostAddress}}/api/score/

# POST request to submit answers
POST {{MyProject.Api_HostAddress}}/api/questionnaire/
Content-Type: application/json

{
  "email": "user@example.com",
  "answers": {
    "1": ["Paris"],
    "2": ["C#", "C"]
  }
}